paths:
  input_raw: /home/mathias/study/bausero/actasal2024
  output_clean: /home/mathias/study/bausero/actas_cleaned
  output_tokens: data_tokens

cleaning:
  remove_accents: true
  to_lower: true
  remove_urls: true
  remove_numbers: true
  keep_only_letters: true

normalization:
  plural: true

synonyms:
  embarcacion: [barco, barca, bote, lancha]
  deportivo: [deporte, deportiva, deportiv]
  pescador: [pescador, pescadora, pescadores]
  prefectura: [prefectura, prefecturas, pnn]
  tramite: [tramite, tramites, trámite, trámites, tramitar]

tokenization:
  ngram: 2
  min_word_length: 3

language: es
